const PUZZLE = {
  CELL_TYPE: {
    EMPTY: "PUZZLE/CELL_TYPE/EMPTY",
    FILL: "PUZZLE/CELL_TYPE/FILL",
    MARK: "PUZZLE/CELL_TYPE/MARK",
  },
  SIZE: {
    "10X10": "PUZZLE/SIZE/10X10",
  },
};

export default PUZZLE;
